//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainerKit.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TrainerKit.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load settings.
        /// </summary>
        internal static string CommandLoadDescription {
            get {
                return ResourceManager.GetString("CommandLoadDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loaded {0}.
        /// </summary>
        internal static string CommandLoadSuccessFormat {
            get {
                return ResourceManager.GetString("CommandLoadSuccessFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save settings.
        /// </summary>
        internal static string CommandSaveDescription {
            get {
                return ResourceManager.GetString("CommandSaveDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Be careful when updating this file :)
        ///For keys, use https://docs.unity3d.com/ScriptReference/KeyCode.html
        ///Colors are stored as an array of &apos;RGBA&apos; floats.
        /// </summary>
        internal static string CommandSaveHeader {
            get {
                return ResourceManager.GetString("CommandSaveHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved {0}.
        /// </summary>
        internal static string CommandSaveSuccessFormat {
            get {
                return ResourceManager.GetString("CommandSaveSuccessFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is {1} {2}.
        /// </summary>
        internal static string CommandStatusTextFormat {
            get {
                return ResourceManager.GetString("CommandStatusTextFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to load {0}. {1}.
        /// </summary>
        internal static string ErrorCannotLoadFormat {
            get {
                return ResourceManager.GetString("ErrorCannotLoadFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to save {0}. {1}.
        /// </summary>
        internal static string ErrorCannotSaveFormat {
            get {
                return ResourceManager.GetString("ErrorCannotSaveFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} seems corrupted. Please fix.
        /// </summary>
        internal static string ErrorCorruptedFileFormat {
            get {
                return ResourceManager.GetString("ErrorCorruptedFileFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} seems corrupted in {1}. Please fix.
        /// </summary>
        internal static string ErrorCorruptedPropertyFormat {
            get {
                return ResourceManager.GetString("ErrorCorruptedPropertyFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} not found!.
        /// </summary>
        internal static string ErrorFileNotFoundFormat {
            get {
                return ResourceManager.GetString("ErrorFileNotFoundFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported type: {0}.
        /// </summary>
        internal static string ErrorUnsupportedTypeFormat {
            get {
                return ResourceManager.GetString("ErrorUnsupportedTypeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This main popup window..
        /// </summary>
        internal static string FeatureCommandsDescription {
            get {
                return ResourceManager.GetString("FeatureCommandsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commands.
        /// </summary>
        internal static string FeatureCommandsName {
            get {
                return ResourceManager.GetString("FeatureCommandsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ironcast-TrainerKit.
        /// </summary>
        internal static string FeatureCommandsTitle {
            get {
                return ResourceManager.GetString("FeatureCommandsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Experience allows to earn extra health and abilities.
        /// </summary>
        internal static string FeatureGetExperienceDescription {
            get {
                return ResourceManager.GetString("FeatureGetExperienceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Experience.
        /// </summary>
        internal static string FeatureGetExperienceName {
            get {
                return ResourceManager.GetString("FeatureGetExperienceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scrap is the currency of Ironcast.
        /// </summary>
        internal static string FeatureGetScrapsDescription {
            get {
                return ResourceManager.GetString("FeatureGetScrapsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Scraps.
        /// </summary>
        internal static string FeatureGetScrapsName {
            get {
                return ResourceManager.GetString("FeatureGetScrapsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to War assets reduce the difficulty of Boss encounters.
        /// </summary>
        internal static string FeatureGetWarAssetsDescription {
            get {
                return ResourceManager.GetString("FeatureGetWarAssetsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get War Assets.
        /// </summary>
        internal static string FeatureGetWarAssetsName {
            get {
                return ResourceManager.GetString("FeatureGetWarAssetsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ammo is used to activate weapons.
        /// </summary>
        internal static string FeatureMaxAmmoDescription {
            get {
                return ResourceManager.GetString("FeatureMaxAmmoDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Ammo.
        /// </summary>
        internal static string FeatureMaxAmmoName {
            get {
                return ResourceManager.GetString("FeatureMaxAmmoName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coolant is used when a system is activated.
        /// </summary>
        internal static string FeatureMaxCoolantDescription {
            get {
                return ResourceManager.GetString("FeatureMaxCoolantDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Coolant.
        /// </summary>
        internal static string FeatureMaxCoolantName {
            get {
                return ResourceManager.GetString("FeatureMaxCoolantName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Energy is used to activate defensive systems.
        /// </summary>
        internal static string FeatureMaxEnergyDescription {
            get {
                return ResourceManager.GetString("FeatureMaxEnergyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Energy.
        /// </summary>
        internal static string FeatureMaxEnergyName {
            get {
                return ResourceManager.GetString("FeatureMaxEnergyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Health of your Ironcast.
        /// </summary>
        internal static string FeatureMaxHealthDescription {
            get {
                return ResourceManager.GetString("FeatureMaxHealthDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Health.
        /// </summary>
        internal static string FeatureMaxHealthName {
            get {
                return ResourceManager.GetString("FeatureMaxHealthName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repair damaged systems in battle.
        /// </summary>
        internal static string FeatureMaxRepairDescription {
            get {
                return ResourceManager.GetString("FeatureMaxRepairDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Repair.
        /// </summary>
        internal static string FeatureMaxRepairName {
            get {
                return ResourceManager.GetString("FeatureMaxRepairName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [summary].
        /// </summary>
        internal static string FeatureRendererSummary {
            get {
                return ResourceManager.GetString("FeatureRendererSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Ironcast-TrainerKit !.
        /// </summary>
        internal static string FeatureRendererWelcome {
            get {
                return ResourceManager.GetString("FeatureRendererWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        internal static string PropertyAmount {
            get {
                return ResourceManager.GetString("PropertyAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cache time (sec).
        /// </summary>
        internal static string PropertyCacheTimeInSec {
            get {
                return ResourceManager.GetString("PropertyCacheTimeInSec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        internal static string PropertyColor {
            get {
                return ResourceManager.GetString("PropertyColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Console Color.
        /// </summary>
        internal static string PropertyConsoleColor {
            get {
                return ResourceManager.GetString("PropertyConsoleColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance.
        /// </summary>
        internal static string PropertyDistance {
            get {
                return ResourceManager.GetString("PropertyDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        internal static string PropertyEnabled {
            get {
                return ResourceManager.GetString("PropertyEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key.
        /// </summary>
        internal static string PropertyKey {
            get {
                return ResourceManager.GetString("PropertyKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X.
        /// </summary>
        internal static string PropertyX {
            get {
                return ResourceManager.GetString("PropertyX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y.
        /// </summary>
        internal static string PropertyY {
            get {
                return ResourceManager.GetString("PropertyY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to off.
        /// </summary>
        internal static string TextOff {
            get {
                return ResourceManager.GetString("TextOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to on.
        /// </summary>
        internal static string TextOn {
            get {
                return ResourceManager.GetString("TextOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ------.
        /// </summary>
        internal static string TextSeparator {
            get {
                return ResourceManager.GetString("TextSeparator", resourceCulture);
            }
        }
    }
}
